name: jobhubs
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  provider:
  dio: ^5.4.3+1
  flutter_svg:
  flutter_vector_icons:
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  get:
  flutter_zoom_drawer: ^3.2.0
  flutter_animate: ^4.5.0
  image_cropper: ^6.0.0
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  intl: ^0.19.0
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  http: ^1.2.1
  pretty_dio_logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
